### PR TITLE
Add kinesis firehose

### PR DESCRIPTION
**Pull request by l0st3d**
I've added support for Kinesis Firehose, which I'll need for a project. This is my first attempt at contributing to this project, so I hope it makes sense ;)

Many thanks,

Ed

### CODE REVIEW

**Comment by mcohen01** [comment]
Ed, this looks great. But I merged a Kinesis Firehose PR from someone just before this came in. They don't have any of the api improvements you included though, they basically just added the kinesisfirehose.clj file, as well as some good docs from others. Is it possible for you to amend this PR to work off the current master? I'd really appreciate it.

Also, I apologize, it's been a while since I've done anything with Kinesis, can you give just a brief description of what the function interceptors are doing? 

And thanks for the kickass tests!

**Comment by l0st3d** [comment]
Hi,

I've merged my stuff in a way which I think won't break the existing code, but which includes the helpers that I added.

amazonica.aws.kinesisfirehose/list-delivery-streams

This wrapper gets around the pagination in the API, so that if there's more streams than are listed in a single page, we do more requests to get the whole list. You can also provide a limit to only get n streams and a exclusive-start-delivery-stream-name if you want to skip that feature.

amazonica.aws.kinesisfirehose/put-record and amazonica.aws.kinesisfirehose/put-record-batch

These both convert to data to instances of ByteBuffer if they can. Sequences are treated as tabular data, so that you can ingest data into RedShift easily.

I've also added to the docs a little, to try and explain these.

Hope this makes sense.

**Comment by mcohen01** [comment]
Thanks Ed! The one thing I forgot to mention, where you're using `alter-var-root`, do these functions support passing either a map or (i forget the term people use for it...) unenclosed key-value pairs (in varargs style) to the function? As in, I can call `foobar` either way:
```clj
(foobar {:a 1})```
or 
```clj
(foobar :a 1)```
and both ways with an optional credentials arg as the first parameter too. I know the community today dislikes unenclosed key-value pairs, but the rest of the api supports both styles and I would prefer not to break with that convention if possible. There's an example of handling both cases at https://github.com/mcohen01/amazonica/blob/master/src/amazonica/aws/sqs.clj#L31

**Comment by l0st3d** [comment]
Yes. If you check the tests, they demonstrate both forms.

**Comment by mcohen01** [comment]
Awesome. Thanks Ed! 0.3.38 is on clojars

**Pull request merged**
