### PR TITLE
Use v2 model interfaces in v1 kinesis client library to support graceful shutdown

### PR DESCRIPTION
**Pull request by Limess**
Fixes https://github.com/mcohen01/amazonica/issues/453

See "Updated Interface (Version 2)" in https://docs.aws.amazon.com/streams/latest/dev/kinesis-record-processor-implementation-app-java.html#kinesis-record-processor-implementation-factory-java for details.

This allows users to call `startGracefulShutdown` on the `Worker` instance to shutdown gracefully.

### CODE REVIEW

**Comment by Limess** [comment]
I've now tested this when not using `dynamodb-adaptor-client?` and it works as expected.

To correctly set endpoints/regions, it was necessary to move this to the construction of clients which is done when `dynamodb-adaptor-client?` is set. Otherwise this will no longer error (it now logs at debug, see https://github.com/awslabs/amazon-kinesis-client/pull/305/files) due to trying to set region/endpoint on the cloudwatch/dynamodb/kinesis clients, the setting will still fail, resulting in the incorrect regions being used.

**Comment by Limess** [comment]
I made another iteration on this, realising that there's really no reason to instantiate the dynamodb or cloudwatch clients.

This is now a slight breaking change - the credentials and kinesis/dynamodb/cloudwatch config given to `worker` will now be used for the three clients when `dynamodb-adaptor-client?` is set, this seems like it should be the expected behaviour.

**Comment by mcohen01** [comment]
Sorry, I merged the first one and now this has conflicts. Do you mind resolving them and we'll merge this as well? Sorry, I can barely read clojure code anymore....

**Comment by Limess** [comment]
Yeah sure, will do. Thanks for merging the first one.

**Comment by mcohen01** [comment]
Thank you! `0.3.158` is on clojars.

**Comment by Limess** [comment]
Hmm, ran this and noticed the credentials wiring is incorrect when setting `dynamodb-adaptor-client?` to `true`. I'll look at fixing that wiring and raise another PR.

I only tested the other use case so missed this.

**Comment by Limess** [comment]
Fixed the above in https://github.com/mcohen01/amazonica/pull/456

**Pull request merged**
