### PR TITLE
remove reflection warnings

### LINKED ISSUE #155: Resolve reflection warnings?
Amazonica relies on reflection, but I think the library could resolve some (and maybe all?) reflection warnings unless I'm misunderstanding how it works. 

E.g. one example is `getConstructors` [here](https://github.com/mcohen01/amazonica/blob/a7520faf3b56e29d894ab397548e685588900c38/src/amazonica/core.clj#L379), which could use a type hint of `java.lang.Class`

Is there a specific reason of not adding these types? I can start working on this to resolve these warnings otherwise

### PR DESCRIPTION
**Pull request by reborg**
Fix #155 

Doesn't seem to be so bad in terms of readability. In certain cases, I think it gives more context to understand what the code is doing (with the exception of the `cond->` that possibly reads worse). I was also concerned about seeing my own reflection warnings than those of Amazonica (more than performance issues). Thanks for the lib.

### CODE REVIEW

**Comment by mcohen01** [comment]
Thanks for performing this thankless and tedious task.

Is this PR ready to be merged? I haven't had my head in this library for some time, and I haven't written much Clojure code in a while, and was never very proficient, and on top of all that the tests suck. Generally I'm a little wary of changes to `core.clj` but these seem fine. I started a repl with your changes and called two functions in a single namespace, seems to work fine. How much testing in the repl did you do with these changes? Basically, are you pretty confident these changes won't break anything?

**Comment by reborg** [comment]
Here's what I've done. I've run the tests before and after the changes. The tests are touching a little bit of everything, but because in my AWS account many stuff are not enabled, they sometimes result in exceptions. I did a diff before and after to make sure there are no new exceptions (which is the case, 25 tests, 1 failure, 11 errors).

Now, this is not exhaustive test, as a type cast somewhere might still trip somebody up one day but main functionality seems to be intact. No rush tho, so in the next couple of weeks I'm planning to deploy the modified branch around in prod projects and see what happens.

**Comment by johanatan** [comment]
Any ETA on when this might be released?

**Comment by mcohen01** [comment]
`0.3.124` is on clojars

**Pull request merged**
