### PR TITLE
Use Client Builders instead of constructors.

### PR DESCRIPTION
**Pull request by stanislas**
Hi everyone :)

I have noticed that amazonica uses constructors to create Clients for the different services instead using the Builder classes. Using the Builder classes has some advantages (incl automatic [Region assignment](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html#automatically-determine-the-aws-region-from-the-environment) if you are using a profile (EC2 or local)) and it seems to be the "preferred" way of creating clients (at least all examples I saw from Amazon use them).

I saw no issue on that subject and so I have prepared a commit with the use of builders instead of constructors as discussion starting point. What do you think?

### CODE REVIEW

**Comment by mcohen01** [comment]
I think this might actually be a backwards incompatible change, I'm not sure what the behavior of DefaultCredentialsProviderChain is, that is, I'm not sure that it defaults to the region the instance is running in. If it doesn't, then this would in fact be a breaking change and I'm not inclined to merge it until the Java SDK actually removes the deprecated constructors.

**Comment by stanislas** [comment]
You are probably right: it will affect the way the region is selected (the builders do more stuff that the constructors).
What do you think of an option to use the builders instead of the constructors if someone wants that? I can prepare another PR.

**Comment by mcohen01** [comment]
I'm still unclear what, if any, functional difference there is between the Builders and the deprecated client constructors. For example, the default no-arg [EC2Client](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-ec2/src/main/java/com/amazonaws/services/ec2/AmazonEC2Client.java#L98) constructor uses the `DefaultAWSCredentialsProviderChain` and the default [ClientConfiguration](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/ClientConfigurationFactory.java#L34) which lowers the timeout as long as the system property is set.

**Comment by stanislas** [comment]
I have constructed an [example](https://github.com/stanislas/amazonica/blob/builder-test/src/main/java/amazonica/BuilderTest.java) in Java to illustrate the change of behaviour. You can find it on the branch [`builder-test`](https://github.com/stanislas/amazonica/tree/builder-test) in my clone of amazonica.

The program will just print out the AZ of the first subnet for each VPCs of the current region on the console. It works similarly on a local machine or on a EC2 instance.

For the local machine, configure your default profile to have a default region different that us-east-1. (I use eu-west-1 (Ireland)); in the `.aws/config` file,
```
[default]
region = eu-west-1
```

For the EC2 instance, create an EC2 instance in eu-west-1 with a EC2 instance role with the policy `arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess`.

If you uberjar and run the `amazonica.BuilderTest` class with the argument `builder`, it will use the builder to create the EC2 client, otherwise it will use the deprecated constructor.

If I run the program on my machine and on a EC2 instance set up as above, I get the following.

```
$ java -cp amazonica-0.3.96-stan8-standalone.jar amazonica.BuilderTest builder
eu-west-1a
eu-west-1b
eu-west-1a
eu-west-1c
eu-west-1c
```

```
$ java -cp amazonica-0.3.96-stan8-standalone.jar amazonica.BuilderTest constructor
us-east-1e
```

With the builder, the correct region is selected (eu-west-1); with the deprecated constructor, there is not automatic region selection and the default AWS region is used (us-east-1).

Maybe it is possible to achieve the same behaviour with the constructors. I do not know if it is possible 😅.

**Comment by kjothen** [comment]
In order to use S3-compatible solutions I've been using the Builder pattern mainly because setting an endpoint-url doesn't appear to be supported when creating the Client directly. I thought it worth documenting this approach on this thread, as it works (for me at least!) without any changes to the existing design.

First, I define a function which returns a client, with three unused params:

```
(defn amazon-builder-client
  ([access-key secret-key region endpoint-url bucket-url? _ _ _]
   (if-let [builder (cond-> (AmazonS3ClientBuilder/standard)
                            access-key (.withCredentials (AWSStaticCredentialsProvider. (BasicAWSCredentials. access-key secret-key)))
                            region (.withRegion region)
                            endpoint-url (.withEndpointConfiguration (AwsClientBuilder$EndpointConfiguration. endpoint-url region))
                            bucket-url? (.enablePathStyleAccess))]
     (.build builder))))

```

Next, I override the default client-config with my own. Typically I supply just my endpoint-url and bucket-url? flag, relying on the environment for the credentials.

```
(defclientconfig
  {:amazon-client-fn
   (memoize
     (partial amazon-builder-client
              "<my-access-key>"
              "<my-secret-key>"
              "<my-region>"
              "<my-endpoint-url>"
              true))})
```
This does just enough to work within the existing amazonica.core design, yet enables me to access a S3-compatible object store which only supports path-style access.

**Comment by mcohen01** [comment]
Thanks!

**Comment by eigenhombre** [comment]
@mcohen01 @stanislas This PR / the .100 release seems to break all sorts of stuff for us as seen in the following Gist: https://gist.github.com/eigenhombre/27baa63b55d9f1d5afc5b450e4cb417f.  Other operations throw "unable to load region information from any provider in the chain" exceptions.  We typically use `.aws/credentials` without modification on the Clojure side.  Even the Amazonica "minimum viable snippet" throws an exception.  @mcohen01 does the minimum viable snippet still work for you? If so, is some sort of change to the AWS config setup needed to go from 0.3.99 to 0.3.100 in Amazonica?  Many thanks in advance... heavy Amazonica user here.

**Comment by mcohen01** [comment]
@eigenhombre sorry about that! can you try with `0.3.101`? If that doesn't work i'll revert. thanks!

**Comment by eigenhombre** [comment]
@mcohen01 first thing tomorrow -- thanks!

**Comment by stanislas** [comment]
sorry for the trouble.

**Comment by eigenhombre** [comment]
@mcohen01 @stanislas, the .101 release looks good so far. Many thanks.

**Comment by rafaelrinaldi** [comment]
I am still experiencing this problem. Tried to roll back to `101` but still no success.

**Pull request merged**
