### PR TITLE
Preserve empty maps when unmarshalling a Java object.

### PR DESCRIPTION
**Pull request by jmarianer**
This is important for round-trips to and from DynamoDB.

### CODE REVIEW

**Comment by jmarianer** [comment]
I realize that this is a global solution but I don't know enough about Amazonica to know if this could have unfortunate side-effects outside of DynamoDB.

**Comment by mcohen01** [comment]
This seems reasonable enough, unfortunately it is technically a breaking change, and it's in a sensitive area of core. I think it's fine if you move the `(marshall)` fn into the [dynamo namespace](https://github.com/mcohen01/amazonica/blob/master/src/amazonica/aws/dynamodbv2.clj#L23). Maybe you could check for `nil?` as well and only return empty maps when the java map is non-null and empty (not sure if the java sdk returns nulls or empty maps though, so it may be moot).

**Comment by jmarianer** [comment]
That makes sense. I was busy doing other stuff today and may not get to it tomorrow, and I'm going on vacation on Thursday, so if not tomorrow then I'll get back on this as soon as I get back in mid-March.

**Comment by jmarianer** [comment]
Please take a look at my force-push. The change is a bit ugly and copy-pastey (I had to copy the code from marshall to marshall-allow-empty-maps) but I think it's the best way to keep it localized in dynamodb.

Note that round-trips are still not 100% preserved because `{:b foo}` turns into a `HeapByteBuffer`, but that's probably unavoidable without breaking the entire interface.

**Comment by mcohen01** [comment]
LGTM

**Comment by mcohen01** [comment]
`0.3.140` is on clojars

**Pull request merged**
