### PR TITLE
added support for specifying a custom client config

### PR DESCRIPTION
**Pull request by k13gomez**
- added support for specifying a custom client config via with-client-config or to define a default one via defclientconfig.
- also changed how thread-bound dynamic vars are resolved via or macro

### CODE REVIEW

**Comment by k13gomez** [comment]
Please take a look at this PR, it allows using a custom client config for all requests to avoid having to pass the client for each call, see below:
```clojure
(defclientconfig
  {:proxy-host "my-proxy-server"
   :proxy-port 8080})
...
```
or
```clojure
(with-client-config
  {:proxy-host "my-proxy-server"
   :proxy-port 8080}
  ...)
```

**Comment by mcohen01** [comment]
I'm not sure how to feel about this PR. I view the defcredential and with-credential macros now as mistakes in this library made early on, around the time java.jdbc was removing a similar idiom for handling the connection. It seems the community has settled on explicitly passing around this kind of state. But once I realized the mistake, the api had been out there for a while and I was reluctant to remove it. Adding a second instance of it for the client config seems like going in the wrong direction.

**Comment by k13gomez** [comment]
This is not as much of an issue for the credentials because they are automatically obtained by the credentials provided chain via environment variables, a credentials file/profile, or via instance metadata once deployed to AWS.
However, I found it inconvenient to have to pass the Client Configuration for each call to the API using Clojure, when compared to using the Java API directly which allows instantiating a Client class with the desired client configuration and then the client configuration is re-used for any subsequent calls.
The rationale for this PR is when making chained API calls that would require passing the same client configuration over and over, it seems more natural and less repetitive to define it once within the call context of globally for all requests (such as in the case of a proxy).

**Comment by mcohen01** [comment]
Fair point.

**Pull request merged**
