### PR TITLE
Add Kinesis Firehose support

### PR DESCRIPTION
**Pull request by andrioni**
It also bumps the SDK version.

I'll try to add some examples later on another PR, if you don't mind. :)

### CODE REVIEW

**Comment by jwhitlark** [comment]
I played with this a bit, and this is the basic usage I had.  Not sure if there's a better way, without doing the sort of stuff that's in the regular kinesis client.  If you've got a better way of doing it, give me a hint, and I'll write up the docs, if you like.

    (dir amazonica.aws.kinesisfirehose)
    create-delivery-stream
    delete-delivery-stream
    describe-delivery-stream
    list-delivery-streams
    put-record
    put-record-batch
    update-destination


    (kf/list-delivery-streams :Limit 10)
    user> {:delivery-stream-names ["jw-test-firehose"], :has-more-delivery-streams false}


    (import [java.nio ByteBuffer])
    (import [com.amazonaws.services.kinesisfirehose.model Record])

    (def r (Record.))
    (.setData r (ByteBuffer/wrap (.getBytes "foo")))
    (kf/put-record :delivery-stream-name "jw-test-firehose" :record r)

**Comment by andrioni** [comment]
Setting up a coercion for Record would probably help, but you can also just skip creating the record separately to simplify a bit:

```clojure
(put-record cred
            :delivery-stream-name "first-test"
            :record {:data (-> "Test Record"
                               .getBytes
                               ByteBuffer/wrap)})
```

Since when using Firehose there's a good chance to read the data using something other than Clojure, the way the Kinesis client works (using Nippy by default) might be a bit too opinionated, but I'm not sure.

**Comment by jwhitlark** [comment]
Ah! That's what I was missing.  

Personally, I think that reads just fine.  I agree with your opinion on nippy.  It's easy to wrap, if that's what you want.

+1

**Comment by mcohen01** [comment]
Thanks! 0.3.37 has this now.

**Pull request merged**
