### PR TITLE
DynamoDBV2 : properly marshall false boolean values

### LINKED ISSUE #110: dynamodbv2 cannot marshall item containing boolean false
After putting or updating an item to contain a boolean `false`, the item can no longer be marshalled to a Clojure map.

A repl session is worth a thousand words:

```
user> (require '[amazonica.aws.dynamodbv2 :as dynamo])
nil
user> (dynamo/put-item :table-name "rs2-player"
                       :item {:id "123", :foo? true})
{}
user> (dynamo/get-item :table-name "rs2-player"
                       :key {:id {:s "123"}})
{:item {:foo? true, :id "123"}}
user> (dynamo/update-item :table-name "rs2-player"
                          :key {:id {:s "123"}}
                          :attribute-updates {:foo? {:action "PUT", :value false}}
                          :return-values "ALL_NEW")
IllegalArgumentException No matching clause:   amazonica.aws.dynamodbv2/eval380/fn--381 (dynamodbv2.clj:24)
user> (dynamo/get-item :table-name "rs2-player"
                       :key {:id {:s "123"}})
IllegalArgumentException No matching clause:   amazonica.aws.dynamodbv2/eval380/fn--381 (dynamodbv2.clj:24)
```

I expect to have a pull request for this shortly, but I figured it was worth filing an issue to reference in the pull request. :)

### PR DESCRIPTION
**Pull request by jmglov**
Fixes #110

### CODE REVIEW

**Comment by jmglov** [comment]
One thing I don't like about this fix is that the boolean `false` value is marshalled as `nil`. This is due to the top-level implementation of the `IMarshall` protocol in [amazonica.core](https://github.com/mcohen01/amazonica/blob/d9333f6c9a2bc818bddee4343c182ddb5945cffd/src/amazonica/core.clj#L630):

```clj
(extend-protocol IMarshall
  nil
  (marshall [obj] nil)
  ;; [Some code elided]
  
  ; `false` boolean objects (i.e. (Boolean. false)) come out of e.g.
  ; .doesBucketExist, which wreak havoc on Clojure truthiness
  Boolean
  (marshall [obj] (if obj (.booleanValue obj)))
```

@mcohen01, can you shed any light on the decision to marshall only `java.lang.Boolean` "true" as the Clojure `true`? Why not simply call `(.booleanValue obj)` unconditionally?

I'm not nit-picking here, as I expect there is a very good reason for this. That's why I didn't want to change it willy-nilly. :)

**Comment by mcohen01** [comment]
I remember this line well. None other than the esteemed @cemerick added it. Dare I say, it appears to have been an oversight? Perhaps the check should be if-not nil?

**Comment by jmglov** [comment]
Or better yet, `when-not (nil? obj)` :)

Shall I change it and see if anything breaks?

**Comment by cemerick** [comment]
I'm afraid I don't have any insight on this. My contrib here was quite a long time ago, relatively speaking…

**Comment by mcohen01** [comment]
Yeah it looks like that's the right thing to do.

**Comment by jmglov** [comment]
OK, done! It works for Dynamo, but I wasn't able to run the full test suite due to #115. We should probably fix that issue so we can run the test suite to give us more confidence that my change didn't break anything before merging this pull request.

**Comment by jmglov** [comment]
I get 1 failure and 7 errors when running `lein test` against the mcogen01:master branch, and 2 failures, 6 errors when running against this pull request. I don't really know what to make of that.

@mcohen01, were you able to run the test suite with no errors or failures?

**Comment by mcohen01** [comment]
@jmglov I fixed a few of the tests, but haven't found a good solution to create-image in ec2, and the securitytoken test was failing on the command line but passing consistently in the repl, even after restarting the vm and clearing everything out. Thought it might be a timing issue, but it wasn't that either. I'll have another look at those tests when I can. Thanks for the nice work!

**Pull request merged**
