### PR TITLE
support for configurable pluggable cache

### PR DESCRIPTION
**Pull request by mcohen01**
Support for users to provide their own `clojure.core.cache/CacheProtocol` cache instead of the default Clojure memoization of any `Amazon*Client` objects. Basic usage with a Google Guava cache might look something like:

```clojure
(require '[clojure.core.cache :as c])
(require '[com.google.guava]

(import com.google.common.cache.CacheBuilder)

(c/defcache GuavaCache [cache]
  c/CacheProtocol
  (lookup [_ item]
    (.getIfPresent cache item))
  (lookup [_ item not-found]
    (or (.getIfPresent cache item) not-found))
  (has? [_ item]
    (some? (.getIfPresent cache item)))
  (hit [this item] this)
  (miss [_ item result] (.put cache item result) cache)
  (evict [_ e] (.invalidate cache e) cache)
  (seed [_ base] cache))

(def guava (.. (CacheBuilder/newBuilder) build))
(def cache (GuavaCache. guava))

(ec2/describe-instances {:client-config {:client-cache cache}})
```

### CODE REVIEW

**Comment by codahale** [comment]
Do you need to depend on `core.cache`, or could you just accept a `memoize` replacement?

**Comment by codahale** [comment]
I just mention it because I've always found `core.cache` to be incredibly hard to use correctly, whereas stuff like Guava's `LoadingCache` is dead easy. Perhaps the more general approach would be to make `amazon-client*` a public function and add a `:client-constructor` key to `:client-config` with a default value of `(memoize amazon-client*)`. That would enable arbitrary fiddling with the client objects, not just caching.

**Comment by mcohen01** [comment]
>Do you need to depend on core.cache, or could you just accept a memoize replacement?

No real reason other than if someone else wanted to use a different cache impl. I don't have any strong preferences here, and in fact, your suggestion of a `:client-factory` function is probably the best solution.

**Comment by ben-manes** [comment]
fyi,
A good reason for not depending on `core.cache` is that it has [memory leaks](http://dev.clojure.org/jira/browse/CCACHE-32). In that case it is inherent to how LIRS works and requires adding a hard limit on ghost entries. I don't think there is enough active development to have a hard dependency on it. (I also suspect that it isn't very fast, but I haven't added it to my benchmark suite)

**Pull request closed without merging**
